###
// REST WEB SERVICE CLIENT

## NOTE. ONLY POST HANDLES SEPARATE BODY. ALL OTHER REQUESTS FAIL, AND ONLY ACCEPT FULL URL STRING???

## GET REQUESTS
// Handles the three request types included in doGet: getAllFilms, getFilmsByName, getFilmById

### GETALLFILMS (default)
GET http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?action=getallfilms
Accept: application/json

### json
GET http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?action=getallfilms&format=json
Accept: application/json

### xml
GET http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?action=getallfilms&format=xml
Accept: application/xml

### text
GET http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?action=getallfilms&format=text
Accept: application/text


### GETFILMSBYNAME (default)
GET http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?action=getfilmsbyname&filmName=wars
Accept: application/json

### json
GET http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?action=getfilmsbyname&filmName=wars&format=json
Accept: application/json

### xml
GET http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?action=getfilmsbyname&filmName=wars&format=xml
Accept: application/xml

### text
GET http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?action=getfilmsbyname&filmName=wars&format=text
Accept: application/text


### GETFILMBYID
GET http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?action=getfilmbyid&id=10002
Accept: application/json


### POST REQUEST
// Handles addFilm request, included in doPost
POST http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice
Content-Type: application/x-www-form-urlencoded

title=newfilm&year=2020&director=marc&stars=marc&review=brilliant

### PUT REQUEST
// Handles updateFilm request, included in doPut
PUT http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?id=11314&title=newfilm&year=2021&director=MARC COOLING&stars=marc&review=average
Content-Type: application/x-www-form-urlencoded


### DELETE REQUEST
// Handles deleteFilm request, included in doDelete
DELETE http://localhost:8080/REST_03_22_war_exploded/FilmRESTWebservice?id=11315
